# Generated by Django 3.0.3 on 2020-03-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='content',
            field=models.TextField(verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='service',
            name='subTitle',
            field=models.CharField(max_length=200, verbose_name='Subtítulo'),
        ),
    ]
