"""
Django settings for webempresa project.

Generated by 'django-admin startproject' using Django 3.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '%a#!t$rve*@pxg!4w_9g61^zto^r@!gaww@=w!i8v%$+psu%2h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Podemos utilizar ngro para ver esta página en un servidor de prueba
# Solo tenemos que registrar la url que nos da.
# ALLOWED_HOSTS = ['d70d9838a408.ngrok.io']
ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blog',
    'ckeditor',
    'contact',
    'core',
    'pages.apps.PagesConfig',
    'services.apps.ServicesConfig',
    'social.apps.SocialConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'webempresa.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Añadimos el directorio de templates para editar el template del administrador
        # y así poder añadir una imagen.
        'DIRS': [os.path.join(BASE_DIR,'templates/')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                #Se añadio este procesador, lo que hara será
                #que al contexto (el diccionario que le pasamos a los templates)
                #se le pueda agregar información por default de tal forma
                #que podamos acceder a ella en cualquier template a traves del
                # contexto.
                'social.processors.ctx_dict',
            ],
        },
    },
]

WSGI_APPLICATION = 'webempresa.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'webempresarial',   #En el admin:
        'USER': 'estudiante',       #user: link
        'PASSWORD': 'zelda1234',    #password: zelda1234
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'es-mx'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
# Con este STATIC irá a búscar el directorio static.
# Solo para producción...
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# Para que lea imagenes de forma global y no necesariamente 
# que las imagenes estén dentro de una app. 
# Hacemos esto aquí para cargar archivos staticos en el admin y así 
# que cargue las imagenes que le pongamos.
STATICFILES_DIRS = [
  os.path.join(BASE_DIR, "static"),
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

#Ckeditor
#Nos ayudará a agregar herramientas de edición de texto.
#Esto para los campos grandes de texto.
# Del inglés "What You See Is What You Get" o "Lo que ves es lo que consigues".
#Algunas configuraciones: https://docs.hektorprofe.net/django/web-empresarial/personalizando-panel-administrador-parte-3/
#Repositorio: https://github.com/django-ckeditor/django-ckeditor 
#'toolbar': None, #Nos saldrán todas las herramientas.
# El campo que tendrá el contenido del texto deberá tener el filtro safe: obj.content|safe

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Bold', 'Italic ', 'Underline'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 
             'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink']
        ]
    }
}

#Email config
EMAIL_HOST = 'smtp.mailtrap.io'
EMAIL_HOST_USER = 'b9053d48194bb9'
EMAIL_HOST_PASSWORD = '00996310fca9de'
EMAIL_PORT = '2525'



#Email config Google
# Link info: https://support.google.com/mail/answer/7126229?visit_id=637276974276465241-129629702&hl=es-419&rd=1
# Se necesitará autenticación STL para que funcione.
# EMAIL_HOST = 'smtp.gmail.io'
# EMAIL_HOST_USER = 'explotaideas@gmail.com'
# EMAIL_HOST_PASSWORD = 'password'
# EMAIL_PORT = '587'